version: '3.1'

services:

  flask:
    build: .
    container_name: flask
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - ./volumes/mongo:/data/db
        

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: redis
    command: redis-server --save 20 1
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local